# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0002_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='propertyname',
            field=models.CharField(default='Woodchase', max_length=256),
            preserve_default=False,
        ),
    ]
